### ISSUE TITLE
[BUG] Pipeline error - Cannot find module 'azure-pipelines-task-lib/task'

### ISSUE THREAD

**Issue by mikedouglasdev** [microsoft/azure-load-testing#51]
**Describe the bug**
Trying to call the AzureLoadTest task, it fails with the following information.  Looks like the task was just updated to 1.1.90.  I hadn't tried it before to know if it worked with 1.1.89.

==============================================================================
Task         : Azure Load Testing
Description  : Automate performance regression testing with Azure Load Testing
Version      : 1.1.90
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/load-testing/tutorial-cicd-azure-pipelines#azure-load-testing-task
==============================================================================
##[debug]Using node path: /home/vsts/agents/2.198.3/externals/node10/bin/node
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'azure-pipelines-task-lib/task'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/vsts/work/_tasks/AzureLoadTest_b61b360c-31ac-4389-922b-303ea8befde7/1.1.90/index.js:32:12)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
##[error]Exit code 1 returned from process: file name '/home/vsts/agents/2.198.3/externals/node10/bin/node', arguments '"/home/vsts/work/_tasks/AzureLoadTest_b61b360c-31ac-4389-922b-303ea8befde7/1.1.90/index.js"'.
##[debug]Microsoft.VisualStudio.Services.Agent.Util.ProcessExitCodeException: Exit code 1 returned from process: file name '/home/vsts/agents/2.198.3/externals/node10/bin/node', arguments '"/home/vsts/work/_tasks/AzureLoadTest_b61b360c-31ac-4389-922b-303ea8befde7/1.1.90/index.js"'.
   at Microsoft.VisualStudio.Services.Agent.Util.ProcessInvoker.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.ProcessInvokerWrapper.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.DefaultStepHost.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Boolean inheritConsoleHandler, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.NodeHandler.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)

**To Reproduce**
Added task

- task: AzureLoadTest@1
  inputs:
    azureSubscription: 'Visual Studio'
    loadTestConfigFile: 'load/weatherforecast.yaml'
    resourceGroup: 'rg-loadtesting'
    loadTestResource: 'lt-azug-demo'

**Expected behavior**
I would expect it to work or complain about my settings I'm passing in.

AB#1483955

**Comment by ninallam** [comment]
@mikedouglasdev The task is updated to 1.1.91. Can you please confirm if it is working now?

**Comment by mikedouglasdev** [comment]
@ninallam I unfortunately used up my credits in my subscription.  I will retry as soon as it is reactivated.

**Comment by mikedouglasdev** [comment]
I was able to verify this is working now.  Thanks for the quick response.

**Comment by Amrita0987** [comment]
How I will resolve this issue please help
